# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'dimina' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for dimina
  pod 'MMKV', '2.2.2'
  pod 'SSZipArchive', '2.4.3'
  pod 'Alamofire', '5.10.2'

end
