# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'dimina' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Dimina', :path => '../Dimina.podspec'  

end
